package me.chill.settings

const val blush = "https://media.giphy.com/media/6CBGoJnEBbEWs/giphy.gif"
const val blush2 = "https://media.giphy.com/media/4RK7EnRhtkat2/giphy.gif"
const val evilLaugh = "https://media.giphy.com/media/jTU09JLRaYCt2/giphy.gif"
const val fondling = "https://media.giphy.com/media/i1zH4nU1QLQ08/giphy.gif"
const val happy = "https://media.giphy.com/media/SpzdWtMmREEaA/giphy.gif"
const val noWay = "https://media.giphy.com/media/bcORJbp7M3RCM/giphy.gif"
const val puffyCheeks = "https://media.giphy.com/media/rKJwzDhaUpa6I/giphy.gif"
const val wink = "https://media.giphy.com/media/XT30PhqFNSbeM/giphy.gif"
const val shock = "https://media.giphy.com/media/YOwHE7Rhr7UJy/giphy.gif"
const val serve = "https://media.giphy.com/media/D0lbXVPTZ3JSw/giphy.gif"
const val clap = "https://media.giphy.com/media/QQDGBVCAlbsxq/giphy.gif"
const val lost = "https://media.giphy.com/media/RMq8fDCPs57Mc/giphy.gif"
const val myBad = "https://media.giphy.com/media/13z4M9pU3yMiJi/giphy.gif"
